- src/App.tsx
- src/pages/HomeAdmin.tsx
- tsconfig.paths.json
Approval - #14 home admin upload
> #14 home admin upload

- package-lock.json
- package.json
- src/App.tsx
- src/index.tsx
> #40 refreshing access token

- src/App.tsx
- src/pages/ChangePasswordView/ChangePasswordView.tsx
- src/pages/ForgotPasswordView/ForgotPasswordView.tsx
- src/pages/HrHomeView/HrHomeView.tsx
- src/pages/HrSelectedStudentsView/HrSelectedStudentsView.tsx
- src/pages/HrStudentProfileView/HrStudentProfileView.tsx
- src/pages/RegisterView/RegisterView.tsx
- src/pages/StudentView/StudentView.tsx
#31 Added routing config to FE.
> #31 routing config

- package-lock.json
- package.json
- src/Validations/UserValidation.ts
- src/components/ForgotPassword/ForgotPassword.css
- src/components/ForgotPassword/ForgotPassword.tsx
- src/components/RemindPasswordBtn/RemindPasswordBtn.tsx
- src/pages/ForgotPasswordView/ForgotPasswordView.tsx
Added form ForgotPassword and validations folder with user validation schema.
> #13-remind-password-formView

- src/components/AddHR/AddHR.tsx
- src/components/LoginBox/LoginBox.tsx
Added support for sending data from the AddHr form to BE. Validation data from BE.
> #47-Add-Hr-connection-to-BE

- src/components/ForgotPassword/ForgotPassword.tsx
- src/components/LoginBox/LoginBox.tsx
Added support for sending data from the ForgotPasswordView form to BE. Validation of errors.
> #61 - ForgotPasswordView - FE-BE

- src/components/AddHR/AddHR.tsx
#61-Sending-data-from-FE-to-BE-ForgotPasswordView
Fixing bugs, problems with names. Change from 'fullname' => 'fullName.'
> #61-Sending-data-from-FE-to-BE-ForgotPasswordView

- src/common/SmallBtn/SmallBtn.css
- src/common/SmallBtn/SmallBtn.tsx
- src/components/LoginBox/LoginBox.tsx
- src/pages/HomeAdmin/HomeAdmin.css
- src/pages/HomeAdmin/HomeAdmin.tsx
Add props onClick to SmallBtn, cursor pointer, and autocomplete off to password input to prevent show warning in the console.
> #44 Create LogoutBtn component fix#2 

- src/index.css
- src/pages/HomeAdmin/HomeAdmin.css
- src/pages/HomeAdmin/HomeAdmin.tsx
#64 - Added styles for a container of Home Admin view.
> #64 - Added styles for container of Home Admin view

- src/common/AnimatedSecondaryButton/AnimatedSecondaryButton.tsx
- src/common/StructureFileModal/StructureFileModal.css
- src/common/StructureFileModal/StructureFileModal.tsx
- src/components/StudentImport/StudentImport.tsx
Added ReusableButton and StructureFileModal.
> #68-modal-with-imported-students-and-button

- src/App.tsx
- src/index.tsx
- src/pages/HrProfileView/HrProfileView.tsx
- src/pages/LoginView/LoginView.tsx
- src/redux-toolkit/features/user/user-slice.ts
- src/utils/protected-routes.tsx
- src/utils/useAuth.tsx
Added protection to routes. Code is commented.
Added new view to app HrProfileView.tsx.
> #30-Added protection to routes.

- src/App.tsx
- src/common/DisplayAlertModals/DisplayAlertModals.tsx
- src/components/ChangePasswordBox/ChangePasswordBox.tsx
- src/components/LoginBox/LoginBox.tsx
- src/components/RegisterBox/RegisterBox.tsx
- src/pages/LoginView/LoginView.tsx
Added navigation after login in system. Fixed bugs with fetch. Tested all forms.
> #104 - Testing Forms & debugging code.

- src/components/Sidebar/Sidebar.css
- src/components/Sidebar/Sidebar.tsx
A Sidebar component has been created for the StudentView.
Styles have been added.
Added logic for passing data by props.
> #81 Sidebar component StudentView

- src/components/RegisterBox/RegisterBox.tsx
- src/components/Sidebar/Sidebar.css
- src/components/Sidebar/Sidebar.tsx
Component Sidebar created.
Prepared for backend connection.
Navigation has been added after registering a user's password on the login page.
> #88- Sidebar Component HrProfileView

- src/components/Header/Header.tsx
- src/components/HrProfileBox/HrProfileBox.css
- src/components/HrProfileBox/HrProfileBox.tsx
- src/components/Sidebars/Sidebar.css
- src/components/Sidebars/SidebarHr.tsx
- src/components/StudentBox/StudentBox.css
- src/components/StudentBox/StudentBox.tsx
- src/components/StudentForm/StudentForm.tsx
HrProfileView connection to BE. Sending props to components. Changing the logic of displaying elements in the following components: HrProfileBox.tsx, Header.tsx, SidebarHr.tsx, StudentForm. 
Added error handling and displaying using the modal component.
> #94 - HrProfileView FE-BE Connection

- src/components/HrProfileBox/HrProfileBox.tsx
one little necessary change :)
> Changed value in users_id_list in HrProfileBox

- src/components/HrProfileBox/HrProfileBox.tsx
- src/components/HrStudentProfileBox/HrStudentProfileBox.tsx
- src/components/StudentBox/StudentBox.tsx
- src/components/StudentExpectations/StudentExpectations.css
- src/components/StudentExpectations/StudentExpectations.tsx
- src/components/StudentForm/StudentForm.tsx
- src/components/StudentGrades/StudentGrades.css
- src/components/StudentGrades/StudentGrades.tsx
- src/components/StudentInfoBoxes/StudentInfoBox.css
- src/components/StudentInfoBoxes/StudentInfoBoxCourses.tsx
- src/components/StudentInfoBoxes/StudentInfoBoxEducation.tsx
- src/components/StudentInfoBoxes/StudentInfoBoxWorkExperience.tsx
- src/components/StudentInfoBoxesLinks/StudentInfoBoxLinksGroupProject.tsx
- src/components/StudentInfoBoxesLinks/StudentInfoBoxLinksPassingProject.tsx
- src/components/StudentInfoBoxesLinks/StudentInfoBoxLinksPortfolio.tsx
- src/index.css
HrStudentProfileView connection to BE. Sending props to components. Changing the logic of displaying elements in the following components: HrStudentProfileBox.tsx, StudentBox.tsx, StudentExpectations.tsx, StudentForm.tsx, StudentGrades.tsx, StudentBox.tsx etc.
Added error handling and displaying using the modal component.
Changing some styles in components.
> #97 - HrStudentProfileView FE-BE Connection

- src/App.tsx
- src/components/HrProfileBox/HrProfileBox.tsx
- src/components/Sidebars/SidebarStudent.tsx
- src/components/StudentExpectations/StudentExpectations.css
- src/components/StudentGrades/StudentGrades.css
- src/components/StudentInfoBoxes/StudentInfoBox.css
HrStudentProfileView connection to BE. Sending props to components. Connecting the login session refresh and path protection. Fixed css bugs and styles.
> #132 - Protected routes & login session refresh.

- src/components/LoginBox/LoginBox.tsx
Adding a login check to loginView.
> #132 - Added Validation to LoginView.

- src/components/HeaderMenu/HeaderMenu.tsx
- src/components/HrProfileBox/HrProfileBox.tsx
- src/components/HrStudentProfileBox/HrStudentProfileBox.tsx
- src/components/LoginBox/LoginBox.tsx
- src/components/Sidebars/SidebarStudent.tsx
- src/components/StudentBox/StudentBox.tsx
- src/components/StudentForm/StudentForm.tsx
Corrected fetchs after changes to BE, changed a few interfaces and improved navigation in application views.
> #131 changes new customer requirements

- src/App.tsx
- src/components/HeaderMenu/HeaderMenu.tsx
- src/components/HrProfileBox/HrProfileBox.tsx
- src/components/LoginBox/LoginBox.tsx
- src/components/Sidebars/SidebarHr.tsx
- src/components/StudentBox/StudentBox.tsx
- src/components/StudentForm/StudentForm.tsx
- src/pages/LoginView/LoginView.tsx
- src/redux-toolkit/features/user/user-slice.ts
- src/utils/protected-routes.tsx
Optimizing the rendering of views. Passing props to higher-order components. Repair of displaying photo previews for HR, repair of displaying information for a student about the visibility of his profile.
> #138 - View-Rendering-Optimization

- src/App.tsx
- src/components/HeaderMenu/HeaderMenu.tsx
- src/components/HrFilterStudentsForm/HrFilterStudentsForm.tsx
- src/components/HrHomeBox/HrHomeBox.tsx
- src/components/HrHomeSingleStudent/HrHomeSingleStudent.tsx
- src/components/LoginBox/LoginBox.tsx
- src/components/SearchByFilterForHRHome/SearchByFilterForHRHome.tsx
- src/components/Sidebars/SidebarHr.tsx
- src/components/StudentGradesAndExpectationsForHR/StudentGradesAndExpectationsForHR.tsx
- src/redux-toolkit/features/user/user-slice.ts
Added FE-BE connection to HrHomeView.
> #124 - Added FE-BE connection to HrHomeView.

- src/components/SearchByFilterForHRHome/SearchByFilterForHRHome.tsx
- src/redux-toolkit/features/user/user-slice.ts
A new reducer has been added to the global state of redux, and a new reducer has been added: filteredUsers. A list filtering method is attached.
> #125-HrHome-searchbar

- src/components/HrFilterStudentsForm/HrFilterStudentsForm.tsx
- src/components/HrHomeBox/HrHomeBox.tsx
- src/components/HrHomeSingleStudent/HrHomeSingleStudent.tsx
- src/components/HrSelectedStudentsBox/HrSelectedStudentsBox.tsx
- src/components/OneSelectedStudentOnList/OneSelectedStudentOnList.tsx
- src/components/StudentGradesAndExpectationsForHR/StudentGradesAndExpectationsForHR.tsx
- src/redux-toolkit/features/user/user-slice.ts
Added connection FE-BE to HrSelectedStudentsBox.tsx.
> #123 - HrSelectedStudentsView FE-BE Connection

- src/components/HrFilterStudentsForm/HrFilterStudentsForm.tsx
- src/components/HrHomeBox/HrHomeBox.tsx
- src/components/HrHomeSingleStudent/HrHomeSingleStudent.tsx
- src/components/HrSelectedStudentsBox/HrSelectedStudentsBox.tsx
- src/components/OneSelectedStudentOnList/OneSelectedStudentOnList.tsx
- src/components/SearchByFilterForHRHome/SearchByFilterForHRHome.tsx
- src/redux-toolkit/features/user/user-slice.ts
Writing a new reducer in redux, connecting the filtering to searchbar.
> #123-Searchbar-HrSelectedStudentsView
